name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: nuget/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore src\CHIMP\CHIMP.sln

    - name: Build solution (Release)
      run: msbuild src\CHIMP\CHIMP.sln /p:Configuration=Release /p:Platform="Any CPU"

    - name: Create release package
      run: |
        mkdir release-package
        copy "src\CHIMP\CHIMP\bin\Release\*.exe" release-package\
        copy "src\CHIMP\CHIMP\bin\Release\*.dll" release-package\
        copy "src\CHIMP\CHIMP\bin\Release\*.config" release-package\

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: CHIMP-Release
        path: release-package\

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: CHIMP-Release
        path: release-package

    - name: Create ZIP
      run: |
        Compress-Archive -Path release-package\* -DestinationPath CHIMP-${{ github.ref_name }}.zip

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: CHIMP-${{ github.ref_name }}.zip
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
